#!/usr/bin/env python

import cgi
import os
import re

ps = cgi.FieldStorage()
pat = ps.getvalue('namere')
if not pat:
    pat = '.*'
if pat[-1] != '$':
    pat += '$'

root = '/cow'
repos = [d for d in os.listdir(root) if (
    os.path.isdir(os.path.join(root, d)) and re.match(pat, d))]

nvs = ['{ "name": "%s", "value": "%s" }' % (d, os.path.join(root, d))
       for d in repos]

print ('Content-type: application/json\n')
print ('[%s]\n' % ','.join(nvs))

